---
title: "elena_skin_analysis"
author: "Peter Higgins"
date: "3/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(here)
library(janitor)
library(gt)
library(flextable)
library(gtsummary)
library(rstatix)
library(likert)
```

## Read in data

Start with FCP and CRP

```{r labs}
fcp <- readxl::read_excel(here("Oct FCP and CRP for charts.xlsx"), sheet = "FCP") %>% 
  group_by(mrn) %>% 
  arrange(mrn, desc(time_point)) %>% 
  mutate(delta_fcp = value - lag(value)) %>% 
  mutate(pct_change_fcp = 100*delta_fcp/lag(value)) %>% 
  ungroup() %>% 
  select(group:pct_change_fcp)

crp <- readxl::read_excel(here("Oct FCP and CRP for charts.xlsx"), sheet = "CRP") %>% 
  group_by(mrn) %>% 
  arrange(mrn, desc(time_point)) %>% 
  mutate(delta_crp = value - lag(value)) %>% 
  mutate(pct_change_crp = 100*delta_crp/lag(value)) %>% 
  ungroup() %>% 
  select(group:pct_change_crp)
```

Now read in Likert values

```{r likert}
path_likert <- readxl::read_excel(here("Oct Likert Numbers.xlsx"), sheet = "path") %>% 
  select(group:path_likert)

endo_likert <- readxl::read_excel(here("Oct Likert Numbers.xlsx"), sheet = "endo") %>% 
  select(group:endo_likert)

imaging_likert <- readxl::read_excel(here("Oct Likert Numbers.xlsx"), sheet = "imaging") %>% 
  select(group:imaging_likert)
```

Now read in demographics

```{r demog}
demog <- readxl::read_excel(here("Oct demographics organized.xlsx")) %>% clean_names() %>% 
  select(group_type:stelara_start) %>% 
  mutate(dob = as.Date(dob),
         stelara_start = as.Date(stelara_start)) %>% 
  rename(group = group_type)
```

## Demographic table with gtsummary and flextable

```{r demographics}
 demog %>% 
   select(-dob, -stelara_start) %>% 
   tbl_summary(
    by = group, # split table by group
    missing = "no" # don't list missing data separately
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 

```

## Testing FCP and CRP

You can also embed plots, for example:

```{r fcp, echo=FALSE}
fcp %>% 
  filter(time_point == "AFTER") %>% 
  rstatix::t_test(value ~ group)

fcp %>% 
  filter(time_point == "BEFORE") %>% 
  rstatix::t_test(value ~ group)

fcp %>% 
  filter(time_point == "AFTER") %>% 
  rstatix::t_test(pct_change_fcp ~ group, detailed = TRUE)
```

```{r crp, echo=FALSE}
crp %>% 
  filter(time_point == "AFTER") %>% 
  rstatix::t_test(value ~ group)

crp %>% 
  filter(time_point == "BEFORE") %>% 
  rstatix::t_test(value ~ group)

crp %>% 
  filter(time_point == "AFTER") %>% 
  rstatix::t_test(pct_change_crp ~ group, detailed = TRUE)
```

## Testing Likert for Path, Endo, Imaging

Use likert package examples

<https://github.com/jbryer/likert>

```{r path, echo=FALSE}

```

```{r endo, echo=FALSE}

```

```{r imaging, echo=FALSE}

```
